workflows:
  ios:
    name: iOS Build
    max_build_duration: 60
    os: macos
    environment:
      flutter: 3.13.9
      xcode: latest
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
